import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Grid, Skeleton } from "@mantine/core";
import Link from "next/link";
import { Footer } from "../components/footer";

const child = (
  <Skeleton height={80} radius="md" animate={false} visible={false} />
);

const customButton = (text: string) => {
  return (
    <Link href={"/people/1"}>
      <button className="flex w-full justify-center align-middle underline underline-offset-4">
        {text}
      </button>
    </Link>
  );
};
const Home: NextPage = () => {
  const router = useRouter();
  const { page } = router.query;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="flex h-screen flex-col  overflow-x-hidden bg-cover bg-center bg-no-repeat text-white md:overflow-y-auto "
        style={{
          backgroundImage: `url("/images/hero-image.jpg")`,
        }}
      >
        <div className="flex-1 pt-32">
          <Grid className="bg-transparent text-2xl ">
            <Grid.Col xs={4}>{customButton("movies")}</Grid.Col>
            <Grid.Col className="bg-transparent text-white" xs={8}>
              {child}
            </Grid.Col>
            <Grid.Col xs={9}>{child}</Grid.Col>
            <Grid.Col xs={3}>{customButton("people")}</Grid.Col>
            <Grid.Col xs={3}>{customButton("starships")}</Grid.Col>
            <Grid.Col xs={4}>{child}</Grid.Col>
            <Grid.Col xs={5}>{child}</Grid.Col>
            <Grid.Col xs={5}>{child}</Grid.Col>
            <Grid.Col xs={3}>{child}</Grid.Col>
            <Grid.Col xs={3}>{customButton("planets")}</Grid.Col>
          </Grid>
        </div>
        <Footer />
      </div>
    </>
  );
};

export default Home;
